// packages/react-query/src/QueryClientProvider.tsx
import * as React from 'react'

import type { QueryClient } from '@tanstack/query-core'
import type { ContextOptions } from './types'

export const defaultContext = React.createContext<QueryClient | undefined>(
  undefined,
)
const QueryClientSharingContext = React.createContext<boolean>(false)

function getQueryClientContext(
  context: React.Context<QueryClient | undefined> | undefined,
) {
  if (context) {
    return context
  }

  return defaultContext
}

export const useQueryClient = ({ context }: ContextOptions = {}) => {
  const queryClient = React.useContext(getQueryClientContext(context))

  if (!queryClient) {
    throw new Error('No QueryClient set, use QueryClientProvider to set one')
  }

  return queryClient
}

type QueryClientProviderPropsBase = {
  client: QueryClient
  children?: React.ReactNode
}
type QueryClientProviderPropsWithContext = ContextOptions &
  QueryClientProviderPropsBase

export type QueryClientProviderProps = QueryClientProviderPropsWithContext

export const QueryClientProvider = ({
  client,
  children,
  context,
}: QueryClientProviderProps): JSX.Element => {
  React.useEffect(() => {
    client.mount()
    return () => {
      client.unmount()
    }
  }, [client])

  const Context = getQueryClientContext(context)

  return (
    <QueryClientSharingContext.Provider value={!context}>
      <Context.Provider value={client}>{children}</Context.Provider>
    </QueryClientSharingContext.Provider>
  )
}

// packages/solid-query/src/QueryClientProvider.tsx
import type { QueryClient } from '@tanstack/query-core'
import type { Context, JSX } from 'solid-js'
import { createContext, useContext, onMount, onCleanup } from 'solid-js'
import type { ContextOptions } from './types'

export const defaultContext = createContext<QueryClient | undefined>(undefined)
const QueryClientSharingContext = createContext<boolean>(false)

function getQueryClientContext(
  context: Context<QueryClient | undefined> | undefined,
) {
  if (context) {
    return context
  }

  return defaultContext
}

export const useQueryClient = ({ context }: ContextOptions = {}) => {
  const queryClient = useContext(getQueryClientContext(context))

  if (!queryClient) {
    throw new Error('No QueryClient set, use QueryClientProvider to set one')
  }

  return queryClient
}

type QueryClientProviderPropsBase = {
  client: QueryClient
  children?: JSX.Element
}
type QueryClientProviderPropsWithContext = ContextOptions &
  QueryClientProviderPropsBase

export type QueryClientProviderProps = QueryClientProviderPropsWithContext

export const QueryClientProvider = (
  props: QueryClientProviderProps,
): JSX.Element => {
  onMount(() => {
    props.client.mount()
  })
  onCleanup(() => props.client.unmount())

  const QueryClientContext = getQueryClientContext(props.context)

  return (
    <QueryClientSharingContext.Provider value={!props.context}>
      <QueryClientContext.Provider value={props.client}>
        {props.children}
      </QueryClientContext.Provider>
    </QueryClientSharingContext.Provider>
  )
}
